//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microservices.Channels.MSSQL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class appsetiings : global::System.Configuration.ApplicationSettingsBase {
        
        private static appsetiings defaultInstance = ((appsetiings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new appsetiings())));
        
        public static appsetiings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
